version: "3.7"

services:
  crawler:
    build:
      context: ./crawler
    volumes:
      - ./crawler:/app
    stdin_open: true
    tty: true
    environment:
      - MONGO_URI=mongodb://admin:abc@mongo:27017
      - MONGO_DB=scraped_data
      - POSTGRES_DETAILS=dbname=simple_news_feed user=admin password=abc host=postgres
    depends_on:
      - mongo
      - postgres
    networks:
      - simple_news_feed

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: abc
    expose:
      - 27017
    ports:
      - 28000:27017
    volumes:
      - mongo_data:/db
    networks:
      - simple_news_feed

  sqitch:
    image: sqitch/sqitch:v1.3.1
    volumes:
      - ./sqitch:/repo
    networks:
      - simple_news_feed

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=simple_news_feed
    expose:
      - 5432
    ports:
      - 65432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simple_news_feed


volumes:
  mongo_data:
  postgres_data:

networks:
  simple_news_feed: